name: U-TV Ultimate Sync
on:
  schedule:
    - cron: '30 1,3,9,12,14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and Process Data
        env:
          TMDB_KEY: ${{ secrets.TMDB_API_KEY }}
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # 1. Get Trending Movie (Fixed JSON Parsing)
          MOVIE_DATA=$(curl -s
